//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushToPlay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityMessage
    {
        public int Id { get; set; }
        public Nullable<int> BaseId { get; set; }
        public Nullable<int> BaseType { get; set; }
        public Nullable<int> TargetID { get; set; }
        public Nullable<int> TargetType { get; set; }
        public string Message { get; set; }
        public Nullable<int> MessageType { get; set; }
        public Nullable<int> MessageAction { get; set; }
        public Nullable<int> ReplyToMessage { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
