//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushToPlay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.GameDetails = new HashSet<GameDetail>();
            this.Genres = new HashSet<Genre>();
            this.UserGames = new HashSet<UserGame>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long GiantBombID { get; set; }
        public string Aliases { get; set; }
        public Nullable<int> MetacriticScore { get; set; }
        public string MetacriticUrl { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Developer { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> SteamAppId { get; set; }
        public string SteamAppUrl { get; set; }
    
        public virtual ICollection<GameDetail> GameDetails { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
        public virtual ICollection<UserGame> UserGames { get; set; }
    }
}
