//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushToPlay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameDetail
    {
        public GameDetail()
        {
            this.UserGames = new HashSet<UserGame>();
        }
    
        public int Id { get; set; }
        public int GameId { get; set; }
        public int PlatformId { get; set; }
        public string Price { get; set; }
        public string IconImage { get; set; }
        public string GameImage { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual ICollection<UserGame> UserGames { get; set; }
    }
}
