//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushToPlay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Events = new HashSet<Event>();
            this.UserGroups = new HashSet<UserGroups>();
        }
    
        public int Id { get; set; }
        public int GroupType { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<UserGroups> UserGroups { get; set; }
    }
}
