//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushToPlay.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PushToPlayContext : DbContext
    {
        public PushToPlayContext()
            : base("name=PushToPlayContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Event> Events { get; set; }
        public DbSet<Game> Games { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<Platform> Platforms { get; set; }
        public DbSet<SteamUser> SteamUsers { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<GameDetail> GameDetails { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<UserGame> UserGames { get; set; }
        public DbSet<RelationFriend> RelationFriends { get; set; }
        public DbSet<ActivityMessage> ActivityMessages { get; set; }
        public DbSet<UserGroups> UserGroups { get; set; }
    }
}
