//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushToPlay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationFriend
    {
        public int Id { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int UserTargetId { get; set; }
        public int UserBaseId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
