//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushToPlay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Events = new HashSet<Event>();
            this.UserGames = new HashSet<UserGame>();
            this.RELATIONFRIEND = new HashSet<RelationFriend>();
            this.RELATIONFRIEND1 = new HashSet<RelationFriend>();
            this.UserGroups = new HashSet<UserGroups>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastLogon { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Name { get; set; }
        public string PsnId { get; set; }
        public string OriginId { get; set; }
        public string GamerTag { get; set; }
        public string Description { get; set; }
        public string SkynerdId { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<UserGame> UserGames { get; set; }
        public virtual ICollection<RelationFriend> RELATIONFRIEND { get; set; }
        public virtual ICollection<RelationFriend> RELATIONFRIEND1 { get; set; }
        public virtual ICollection<UserGroups> UserGroups { get; set; }
    }
}
